# local image, containing the scheduler script
FROM scheduler

USER root 

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt --no-cache-dir

RUN useradd app --create-home --shell /bin/bash
USER app

COPY . .

VOLUME /scrape_conf

COPY <<EOF schedule_conf.yaml
jobs: 
- cmd: |
    cd /app && \
    for i in $(ls /scrape_conf)
    do
      python src/main.py \\
        -c /scrape_conf/\$i \\
        --store mongodb \\
        --cache redis \\
        --notifier redis_streams \\
        -l 2
    done

  schedule:
  - every(1).minutes
EOF


# ENTRYPOINT ["python3", "src/main.py"]
ENTRYPOINT ["python3", "/scheduler/src/scheduler.py", "schedule_conf.yaml"]
