# local image, containing the scheduler script
FROM scheduler

USER root 

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt --no-cache-dir

RUN useradd app --create-home --shell /bin/bash
USER app

COPY . .

VOLUME /scrape_conf

COPY <<-EOF schedule_conf.yaml
jobs: 
- cmd: |
    python src/main.py \
    $@

  schedule:
  - every().day.at(20:14)
EOF


ENTRYPOINT ["python3", "src/main.py"]
