jobs: 
# - callable: main:main
- cmd: python src/test.py --opt 12
  env: 
    TEST: foobartest
  schedule:
  - every.seconds
  # args:
  # - -c 
  # - ../investigations/articles_and_configs/scrape_configs/abc_news/business.yaml
  # - -l
  # - '1'
